name: Go Project

on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v4
      - name: Set Up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

      - name: listele
        run: ls -al
      - name: Upload static site content
        uses: actions/upload-artifact@v4
        with:
         name: static-site
         path: .
         include-hidden-files: true
    
